name: Run Python tests

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  tests:
    name: Tests for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: pt
      - name: Install geoopt
        shell: bash -l {0}
        run: pip install --no-deps git+https://github.com/geoopt/geoopt.git
      - name: Download data
        shell: bash -l {0}
        run: python -m data.download
      - name: Flake8
        shell: bash -l {0}
        run: flake8 .
      - name: PyTest
        shell: bash -l {0}
        run: |
            cd ${GITHUB_WORKSPACE?}
            python -m pytest 2>&1

